### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by Icelys** [Icelys/Scotch-Language#5]
- [x] Write more methods
- [x] Add support for codeblocks in functions
- [x] User-Defined functions
- [ ] User-Defined functions with inputs

**Comment by BookOwl** [comment]
Please add lambdas and first class functions.

**Comment by Icelys** [comment]
OK, I added functions. Now I will work on functions with inputs.
